// auto-generated by a js-code-template-generator
import { createSelector } from 'reselect'

export const selectState = id => createSelector(
  StateManager => StateManager[id],
  (asyncState) => asyncState
)

export const selectStates = arrayOfIds => createSelector(
  StateManager => StateManager,
  (StateManager) => {
    return arrayOfIds.reduce((a, c) => {
      a[c] = StateManager[c]
      return a
    }, {})
  }
)
