// auto-generated by a js-code-template-generator
import { createSelector } from 'reselect'

export const makeSelectStates = (ids) => {
  const selectors = ids.map(id => {
    return createSelector(
      state => state.$NAME$?.[id],
      state => ({
        [id]: state
      })
    )
  })
  return createSelector(
    [...selectors],
    (...states) => {
      return states.reduce((accumulator, currentObject) => {
        return { ...accumulator, ...currentObject }
      }, {})
    }
  )
}
