// auto-generated by a js-code-template-generator

export const SET_PENDING = 'SET_PENDING'
export const SET_SUCCESS = 'SET_SUCCESS'
export const SET_ERROR = 'SET_ERROR'
export const CLEAR_ASYNC = 'CLEAR_ASYNC'
